namespace TextFx
{
	public enum ANIMATION_DATA_TYPE
	{
		NONE = 0,
		ALL = 1,
		TEXT_CHANGED = 2,
		ANIMATE_ON = 3,
		ACTION_TYPE = 4,
		LETTER_ANCHOR = 5,
		EASE_TYPE = 6,
		COLOUR = 7,
		POSITION = 8,
		LOCAL_ROTATION = 9,
		GLOBAL_ROTATION = 10,
		LOCAL_SCALE = 11,
		GLOBAL_SCALE = 12,
		FORCE_SAME_START = 13,
		WHITE_SPACES_DELAYS = 14,
		DELAY = 15,
		DURATION = 16,
		AUDIO_EFFECTS = 17,
		PARTICLE_EFFECTS = 18,
		DELAY_EASED_RANDOM_SWITCH = 19,
		NUM_LOOP_ITERATIONS = 20
	}
}
