namespace TextFx
{
	public enum LETTERS_TO_ANIMATE
	{
		ALL_LETTERS = 0,
		FIRST_LETTER = 1,
		FIRST_LETTER_WORDS = 2,
		FIRST_LETTER_LINES = 3,
		LAST_LETTER = 4,
		LAST_LETTER_WORDS = 5,
		LAST_LETTER_LINES = 6,
		CUSTOM = 7,
		FIRST_WORD = 8,
		LAST_WORD = 9,
		NTH_WORD = 10,
		FIRST_LINE = 11,
		LAST_LINE = 12,
		NTH_LINE = 13
	}
}
